<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9656" started-at="2019-09-10T00:47:13Z" finished-at="2019-09-10T00:47:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9656" started-at="2019-09-10T00:47:13Z" finished-at="2019-09-10T00:47:23Z">
      <class name="TC001_GET_Req">
        <test-method status="FAIL" signature="gettest()[pri:0, instance:TC001_GET_Req@13741d5a]" name="gettest" duration-ms="4603" started-at="2019-09-10T00:47:13Z" finished-at="2019-09-10T00:47:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at TC001_GET_Req.gettest(TC001_GET_Req.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gettest -->
        <test-method status="PASS" signature="gettest2()[pri:0, instance:TC001_GET_Req@13741d5a]" name="gettest2" duration-ms="2362" started-at="2019-09-10T00:47:18Z" finished-at="2019-09-10T00:47:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gettest2 -->
        <test-method status="PASS" signature="gettest3()[pri:0, instance:TC001_GET_Req@13741d5a]" name="gettest3" duration-ms="2597" started-at="2019-09-10T00:47:20Z" finished-at="2019-09-10T00:47:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gettest3 -->
      </class> <!-- TC001_GET_Req -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
